# Generated by Django 5.1.5 on 2025-08-18 07:27

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Your project title', max_length=100)),
                ('year', models.CharField(help_text='Year of your project ,e.g 2023', max_length=4)),
                ('client', models.CharField(help_text='Your client, e.g Google', max_length=100)),
                ('service', models.CharField(help_text='Your service, e.g Web Development', max_length=100)),
                ('project_type', models.CharField(help_text='Your project type, e.g Full Stack', max_length=100)),
                ('description', tinymce.models.HTMLField(blank=True, help_text='Write about your project here', null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Your skill, e.g Python', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='YoutubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter YouYube title', max_length=100)),
                ('link', models.URLField(help_text='Video URL')),
                ('thumbnail', models.ImageField(help_text='Youtube video thumbnail', upload_to='image/youtube_thumbnail')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CostumUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_me', tinymce.models.HTMLField(blank=True, help_text='Write about yourself here', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='about_me/image')),
                ('my_name', models.CharField(help_text='Your name', max_length=100)),
                ('social_media', models.JSONField(blank=True, help_text='Add your social media links here e.g {"facebook":"https://www.facebook.com/yourname"}', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('skills', models.ManyToManyField(blank=True, help_text='Select your skills', null=True, to='portfolio.skill')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.CharField(help_text='Start year of your education ,e.g 2019', max_length=4)),
                ('end_year', models.CharField(help_text='End year of your education ,e.g 2023', max_length=4)),
                ('degree', models.CharField(help_text='Your degree, e.g Bachelor of Science', max_length=100)),
                ('university', models.CharField(help_text='Your university, e.g University of California', max_length=100)),
                ('description', tinymce.models.HTMLField(help_text='Write about your education here')),
                ('about_me', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.aboutme')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.CharField(help_text='Start year of your experience ,e.g 2019', max_length=4)),
                ('end_year', models.CharField(help_text='End year of your experience ,e.g 2023', max_length=4)),
                ('position', models.CharField(help_text='Your position, e.g Software Developer', max_length=100)),
                ('company', models.CharField(help_text='Your company, e.g Google', max_length=100)),
                ('description', tinymce.models.HTMLField(help_text='Write about your experience here')),
                ('about_me', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.aboutme')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Uploade your project image', upload_to='project/image')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.project')),
            ],
        ),
    ]
